package com.proyek4.datajabar.utils

class Constant {
    val cityOptions = listOf(
        "KOTA BANDUNG", "KABUPATEN BOGOR", "KOTA BEKASI", "KABUPATEN BANDUNG",
        "KABUPATEN BANDUNG BARAT", "KABUPATEN BEKASI", "KABUPATEN CIAMIS",
        "KABUPATEN CIANJUR", "KABUPATEN CIREBON", "KABUPATEN GARUT", "KABUPATEN INDRAMAYU",
        "KABUPATEN KARAWANG", "KABUPATEN KUNINGAN", "KABUPATEN MAJALENGKA", "KABUPATEN PANGANDARAN",
        "KABUPATEN PURWAKARTA", "KABUPATEN SUBANG", "KABUPATEN SUKABUMI", "KABUPATEN SUMEDANG",
        "KABUPATEN TASIKMALAYA", "KOTA BANJAR", "KOTA BOGOR", "KOTA CIMAHI",
        "KOTA CIREBON", "KOTA DEPOK", "KOTA SUKABUMI", "KOTA TASIKMALAYA"
    )
    val yearOptions = listOf("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018",
        "2019", "2020", "2021", "2022", "2023", "2024")
}